### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [dorothyeves/splurty-app-de#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by dorothyeves** [comment]
I believe I figured it out. I added the code below right before <head> and I tested it and it definitely looks better on mobile on now. I added the shrink-to-no-fit=no as well per the safari browser auto shrinks unless this is specified. 

<meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

**Comment by dorothyeves** [comment]
i have set a commit on git with the updated code. Thanks

**Comment by Mikeysax** [comment]
:+1:
